import { useState } from 'react'
import { Sparkles, Calendar, Mail, Palette, Copy, Check, DollarSign, Target, TrendingUp, BarChart2 } from 'lucide-react'
import Card, { CardHeader } from '../components/ui/Card'
import Button from '../components/ui/Button'
import Badge from '../components/ui/Badge'
import EugeneTyping from '../components/ui/EugeneTyping'
import { simulateTyping } from '../lib/openrouter'

const DEMO_SOCIAL_CALENDAR = `# 30-Day Social Media Calendar
## Lumina Aesthetics | Austin, TX | June 2026

---

**WEEK 1**

**Day 1 (Mon) — Instagram Reel**
Content: "The 5 financial questions you SHOULD be asking at your Botox consultation"
Caption: "Before you book anywhere, you need to understand quality standards and why underpriced units often indicate heavy dilution. 👇 Save this. #AestheticsCFO #BotoxAustin #MedSpaAustin"
Visual: Provider on camera, talking directly, explaining pricing transparency
Time: 9:00am

**Day 2 (Tue) — Story**
Content: Poll — "Do you know what's in your filler syringes?"
Caption: "Quality and FDA-approved sourcing is everything. We never cut corners to inflate margins."
Time: 12:00pm

**Day 3 (Wed) — Educational Carousel**
Content: "How memberships actually save you 15% annually on treatments"
Caption: "The math of a membership: regular dosing schedules mean better long-term results and a steady, planned beauty budget. (Swipe for calculations) #AestheticsMath #LuminaMembership"
Visual: Beautiful, simple financial breakdown of membership packages
Time: 10:00am

---

*Social calendar generated by Eugene's AI — Fractional CFO & Scaling Advisory*`

export default function MarketingStudio({ tab }) {
  const tabs = [
    { key: 'roi', label: 'Marketing ROI & CAC', icon: DollarSign },
    { key: 'social', label: 'Social Calendar', icon: Calendar },
    { key: 'brand', label: 'Brand Builder', icon: Palette },
    { key: 'email', label: 'Email Campaigns', icon: Mail },
  ]
  const [activeTab, setActiveTab] = useState(tab || 'roi')
  const [output, setOutput] = useState('')
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)
  const [brandForm, setBrandForm] = useState({ name: 'Lumina Aesthetics', city: 'Austin', services: 'Botox, fillers, laser', differentiator: 'No-pressure environment, medical expertise' })
  const [emailType, setEmailType] = useState('Re-engagement')

  // CAC & ROI States
  const [monthlySpend, setMonthlySpend] = useState(6000)
  const [leadVolume, setLeadVolume] = useState(120)
  const [leadToConsultRate, setLeadToConsultRate] = useState(45) // 45%
  const [consultToBookRate, setConsultToBookRate] = useState(70) // 70%
  const [avgTicket, setAvgTicket] = useState(750)
  const [annualVisits, setAnnualVisits] = useState(3.2)

  // Calculations
  const costPerLead = leadVolume > 0 ? (monthlySpend / leadVolume) : 0
  const consultsGenerated = Math.round((leadVolume * leadToConsultRate) / 100)
  const patientsAcquired = Math.round((consultsGenerated * consultToBookRate) / 100)
  const customerAcquisitionCost = patientsAcquired > 0 ? Math.round(monthlySpend / patientsAcquired) : 0
  
  const customerLifetimeValue = Math.round(avgTicket * annualVisits)
  const ltvToCac = customerAcquisitionCost > 0 ? (customerLifetimeValue / customerAcquisitionCost).toFixed(1) : 0
  
  const monthlyMarketingRevenue = patientsAcquired * avgTicket
  const marketingRoiMultiple = monthlySpend > 0 ? (monthlyMarketingRevenue / monthlySpend).toFixed(1) : 0

  const generateSocial = () => {
    setLoading(true)
    setOutput('')
    simulateTyping(DEMO_SOCIAL_CALENDAR, c => setOutput(p => p + c), () => setLoading(false), 5)
  }

  const BRAND_OUTPUT = `# Brand Identity Report — Lumina Aesthetics

## Brand Positioning Statement
Lumina Aesthetics is Austin's premier medical aesthetics practice built on transparent pricing, premium clinical expertise, and outstanding client-centered financial stewardship.

## Brand Voice
- Analytical & Elite
- Fully Transparent
- Passionate about safety and outcome integrity

*Recommended Tagline:* "Aesthetics with absolute integrity"`

  const EMAIL_OUTPUT = `**Subject:** [First Name], how has your skin care investment paid off this season?
**Preview text:** Your clinical treatment notes are waiting.

---

Hi [First Name],

It's Eugene Kurkov here, Fractional CFO and director at Lumina Aesthetics. 

When was the last time you reviewed your aesthetic plan? Just like any high-value asset, consistency is key to protecting your initial results. 

We have reserved 4 strategic assessment spots this week. Let's make sure your skin investment matches your long-term aesthetic goals.

**[Secure Your Touch-up & Strategy Session →]**

Talk soon,
Eugene Kurkov
Eugene Consulting & Lumina Aesthetics`

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      {/* Tabs */}
      <div className="flex gap-1 p-1 rounded-xl bg-gray-100 overflow-x-auto" style={{ width: 'fit-content' }}>
        {tabs.map(t => {
          const Icon = t.icon
          return (
            <button key={t.key} onClick={() => setActiveTab(t.key)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-xs font-medium whitespace-nowrap transition-all ${activeTab === t.key ? 'btn-primary text-white shadow-sm' : 'text-gray-500 hover:text-navy-950'}`}>
              <Icon size={14} />{t.label}
            </button>
          )
        })}
      </div>

      {activeTab === 'roi' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="space-y-4">
            <Card>
              <CardHeader title="Funnel Inputs" subtitle="Model marketing spend ROI" icon={Target} />
              <div className="space-y-3.5">
                <div>
                  <label className="text-xs text-gray-500 mb-1 block font-medium">Monthly Ad Spend ($)</label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm">$</span>
                    <input type="number" className="form-input w-full pl-7" value={monthlySpend} onChange={e => setMonthlySpend(Number(e.target.value))} />
                  </div>
                </div>
                <div>
                  <label className="text-xs text-gray-500 mb-1 block font-medium">Total Monthly Lead Intake</label>
                  <input type="number" className="form-input w-full" value={leadVolume} onChange={e => setLeadVolume(Number(e.target.value))} />
                </div>
                <div>
                  <label className="text-xs text-gray-500 mb-1 block font-medium">Lead → Consultation Rate (%)</label>
                  <div className="relative">
                    <input type="number" className="form-input w-full pr-7" value={leadToConsultRate} onChange={e => setLeadToConsultRate(Number(e.target.value))} />
                    <span className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm">%</span>
                  </div>
                </div>
                <div>
                  <label className="text-xs text-gray-500 mb-1 block font-medium">Consultation → Booking Rate (%)</label>
                  <div className="relative">
                    <input type="number" className="form-input w-full pr-7" value={consultToBookRate} onChange={e => setConsultToBookRate(Number(e.target.value))} />
                    <span className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm">%</span>
                  </div>
                </div>
                <div>
                  <label className="text-xs text-gray-500 mb-1 block font-medium">Average Treatment Ticket ($)</label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm">$</span>
                    <input type="number" className="form-input w-full pl-7" value={avgTicket} onChange={e => setAvgTicket(Number(e.target.value))} />
                  </div>
                </div>
                <div>
                  <label className="text-xs text-gray-500 mb-1 block font-medium">Annual Treatment Frequency</label>
                  <input type="number" step="0.1" className="form-input w-full" value={annualVisits} onChange={e => setAnnualVisits(Number(e.target.value))} />
                </div>
              </div>
            </Card>
          </div>

          <div className="lg:col-span-2 space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="glass-card rounded-xl p-4 bg-white">
                <p className="text-xs text-gray-500 font-medium">Cost Per Lead (CPL)</p>
                <p className="text-2xl font-display font-bold text-navy-950 mt-1">
                  ${Math.round(costPerLead)}
                </p>
                <p className="text-[10px] text-gray-400 mt-1">
                  Benchmark: $35–$65 average
                </p>
              </div>
              <div className="glass-card rounded-xl p-4 bg-white">
                <p className="text-xs text-gray-500 font-medium">Customer Acquisition Cost</p>
                <p className="text-2xl font-display font-bold text-indigo-600 mt-1">
                  ${customerAcquisitionCost}
                </p>
                <p className="text-[10px] text-gray-400 mt-1">
                  Target CAC: &lt;${Math.round(avgTicket * 0.3)} (30% ticket)
                </p>
              </div>
              <div className="glass-card rounded-xl p-4 bg-white">
                <p className="text-xs text-gray-500 font-medium">LTV to CAC Ratio</p>
                <p className={`text-2xl font-display font-bold mt-1 ${Number(ltvToCac) >= 3 ? 'text-green-500' : 'text-amber-500'}`}>
                  {ltvToCac}x
                </p>
                <p className="text-[10px] text-gray-400 mt-1 font-medium">
                  {Number(ltvToCac) >= 4 ? 'Elite performance' : Number(ltvToCac) >= 3 ? 'Healthy target' : 'Needs attention'}
                </p>
              </div>
            </div>

            <Card>
              <CardHeader title="Financial Funnel Yield" subtitle="How your marketing opex converts to practice revenue" icon={BarChart2} />
              <div className="space-y-4">
                {[
                  { label: 'Leads Received', val: leadVolume, suffix: ' leads', color: '#8B5CF6' },
                  { label: 'Consultations Run', val: consultsGenerated, suffix: ' consults', color: '#6366F1' },
                  { label: 'Patients Booked', val: patientsAcquired, suffix: ' conversions', color: '#10B981' },
                ].map((row, i) => (
                  <div key={i} className="flex flex-col space-y-1">
                    <div className="flex justify-between text-sm">
                      <span className="text-xs text-gray-500 font-semibold">{row.label}</span>
                      <span className="text-xs font-bold text-navy-950">
                        {row.val}{row.suffix}
                      </span>
                    </div>
                    <div className="h-2 w-full rounded-full bg-gray-100 overflow-hidden">
                      <div
                        className="h-full rounded-full"
                        style={{
                          width: `${Math.round((row.val / leadVolume) * 100)}%`,
                          backgroundColor: row.color,
                        }}
                      />
                    </div>
                  </div>
                ))}
              </div>

              <div className="mt-5 p-3 rounded-xl bg-indigo-50/50 border border-indigo-100 flex items-center justify-between">
                <div>
                  <p className="text-xs text-gray-500 font-medium">Estimated First-Visit Revenue</p>
                  <p className="text-lg font-display font-bold text-navy-950">${(patientsAcquired * avgTicket).toLocaleString()}</p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-gray-500 font-medium">Overall Marketing ROI Multiple</p>
                  <p className="text-lg font-display font-bold text-indigo-600">{marketingRoiMultiple}x</p>
                </div>
              </div>
            </Card>
          </div>
        </div>
      )}

      {activeTab === 'social' && (
        <div className="space-y-4">
          <Card>
            <CardHeader title="30-Day Social Media Calendar" subtitle="AI generates a full month of content strategy" icon={Calendar} />
            <p className="text-xs text-gray-400 mb-4">Pre-configured with Eugene Consulting's editorial messaging rules.</p>
            <Button variant="primary" icon={<Sparkles size={14} />} loading={loading} onClick={generateSocial}>
              Generate 30-Day Calendar
            </Button>
          </Card>
          {output && (
            <Card>
              <div className="flex justify-between items-center mb-3">
                <h3 className="font-display font-semibold text-navy-950">Your Calendar</h3>
                <Button variant="ghost" size="sm" icon={copied ? <Check size={13} /> : <Copy size={13} />}
                  onClick={() => { navigator.clipboard.writeText(output); setCopied(true); setTimeout(() => setCopied(false), 2000) }}>
                  {copied ? 'Copied!' : 'Copy'}
                </Button>
              </div>
              <pre className="whitespace-pre-wrap text-sm text-gray-700 leading-relaxed font-body max-h-[600px] overflow-y-auto">{output}</pre>
            </Card>
          )}
          {loading && !output && <div className="flex justify-center py-8"><EugeneTyping message="Building your social calendar..." /></div>}
        </div>
      )}

      {activeTab === 'brand' && (
        <div className="space-y-4">
          <Card>
            <CardHeader title="Brand Builder" subtitle="Define your practice identity and voice" icon={Palette} />
            <div className="grid grid-cols-2 gap-4 mb-4">
              {[
                { key: 'name', label: 'Practice Name' },
                { key: 'city', label: 'City' },
                { key: 'services', label: 'Core Services' },
                { key: 'differentiator', label: 'What makes you different?' },
              ].map(f => (
                <div key={f.key}>
                  <label className="text-xs text-gray-500 mb-1.5 block font-medium">{f.label}</label>
                  <input className="form-input w-full px-3 py-2.5 rounded-xl text-sm" value={brandForm[f.key]}
                    onChange={e => setBrandForm(b => ({ ...b, [f.key]: e.target.value }))} />
                </div>
              ))}
            </div>
            <Button variant="primary" icon={<Sparkles size={14} />} loading={loading}
              onClick={() => { setLoading(true); setOutput(''); simulateTyping(BRAND_OUTPUT, c => setOutput(p => p + c), () => setLoading(false), 8) }}>
              Build Brand Identity
            </Button>
          </Card>
          {output && (
            <Card>
              <pre className="whitespace-pre-wrap text-sm text-gray-700 leading-relaxed font-body">{output}</pre>
            </Card>
          )}
          {loading && !output && <div className="flex justify-center py-8"><EugeneTyping message="Building your brand..." /></div>}
        </div>
      )}

      {activeTab === 'email' && (
        <div className="space-y-4">
          <Card>
            <CardHeader title="Email Campaign Generator" subtitle="High-converting patient emails, ready to send" icon={Mail} />
            <div className="mb-4">
              <label className="text-xs text-gray-500 mb-2 block font-medium">Campaign Type</label>
              <div className="flex flex-wrap gap-2">
                {['Re-engagement', 'New Patient Welcome', 'Promotional', 'Post-Treatment', 'Membership Offer'].map(t => (
                  <button key={t} onClick={() => setEmailType(t)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${emailType === t ? 'btn-primary text-white shadow-sm' : 'bg-gray-100 text-gray-400 hover:text-navy-950'}`}>
                    {t}
                  </button>
                ))}
              </div>
            </div>
            <Button variant="primary" icon={<Sparkles size={14} />} loading={loading}
              onClick={() => { setLoading(true); setOutput(''); simulateTyping(EMAIL_OUTPUT, c => setOutput(p => p + c), () => setLoading(false), 8) }}>
              Generate Email
            </Button>
          </Card>
          {output && (
            <Card>
              <div className="flex justify-between items-center mb-3">
                <h3 className="font-display font-semibold text-navy-950">{emailType} Email</h3>
                <Button variant="ghost" size="sm" icon={copied ? <Check size={13} /> : <Copy size={13} />}
                  onClick={() => { navigator.clipboard.writeText(output); setCopied(true); setTimeout(() => setCopied(false), 2000) }}>
                  {copied ? 'Copied!' : 'Copy'}
                </Button>
              </div>
              <pre className="whitespace-pre-wrap text-sm text-gray-700 leading-relaxed font-body">{output}</pre>
            </Card>
          )}
          {loading && !output && <div className="flex justify-center py-8"><EugeneTyping message="Writing your email..." /></div>}
        </div>
      )}
    </div>
  )
}
